[versions]
agp = "8.1.0"
kotlin = "1.9.0"
crashlytics = "2.9.7"
google-services = "4.3.15"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
lifecycle-viewmodel-compose = "2.6.1"
lifecycle-runtime-compose = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.01"
firebase-bom = "32.2.0"
appcompat = "1.6.1"
material = "1.9.0"
navigation = "2.6.0"
datastore-prefs = "1.0.0"
hilt = "2.47"
ksp = "1.9.0-1.0.11"
hilt-navigation-compose = "1.0.0"
accompanist = "0.31.5-beta"
room-version = "2.5.2"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose"}
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose"}
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom"}
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
datastore-prefs = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-prefs" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt"}
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose"}
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist"}
accompanist-drawable-painter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist"}
room-runtime = { group="androidx.room", name = "room-runtime", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }
room-testing = {group = "androidx.room", name = "room-testing", version.ref = "room-version"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin"}

